# Generated by Django 3.2.4 on 2021-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='mean_vector',
            field=models.TextField(null=True),
        ),
    ]
