# Generated by Django 3.2.4 on 2021-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifytoken_mean_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expiry',
            field=models.IntegerField(null=True),
        ),
    ]
