# Generated by Django 3.2.4 on 2021-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_spotifytoken_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='top_artists',
            field=models.TextField(null=True),
        ),
    ]
