# Generated by Django 3.2.4 on 2021-06-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('creator', models.CharField(max_length=100, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('songs', models.ManyToManyField(to='api.Songs')),
            ],
        ),
    ]
