# Generated by Django 3.2.4 on 2021-07-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='album_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='songs',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='songs',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='songs',
            name='track_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creator',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='uri',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
